# scripts/constants.gd
class_name GameConstants
extends RefCounted

const VIEWPORT_W := 720
const VIEWPORT_H := 1280

# Enemy wave scaling
const BASE_ENEMY_COUNT := 100
const LEVEL_DIFFICULTY_GROWTH := 1.1
const ENEMIES_PER_ROW := 3
const ROW_HORIZONTAL_SPACING := 150.0
const MAX_ON_SCREEN_ENEMIES := 10
const BASE_ENEMY_SPEED := 144.0
const ENEMY_SPEED_VARIANCE_MIN := 0.85
const ENEMY_SPEED_VARIANCE_MAX := 1.15
const ENEMY_SPEED_EQUALITY_EPSILON := 0.1
const MAX_SPEED_MULTIPLIER := 2.5
const HUD_COMBAT_START_Y := 90.0

# Boss scaling
const BASE_BOSS_HP := 3000.0
const BOSS_DEFEAT_DELAY := 2.0
const BOSS_WARNING_DURATION := 0.5
const BOSS_LEVEL_INTERVAL := 5
const BOSS_BULLET_COUNT_BASE := 5
const BOSS_BULLET_COUNT_PER_LEVEL := 0.0
const BOSS_FIRE_INTERVAL_BASE := 3.0
const BOSS_FIRE_INTERVAL_MIN := 0.8
const BOSS_FIRE_INTERVAL_DECAY := 0.05
const BOSS_ENTER_START_Y := -280.0
const BOSS_PATROL_Y := 240.0
const BOSS_ENTER_SPEED := 120.0
const BOSS_VERTICAL_BOB_AMPLITUDE := 28.0
const BOSS_VERTICAL_BOB_SPEED := 1.4
const BOSS_LIGHTNING_COUNT := 7
const ZIGZAG_HORIZONTAL_FREQ := 2.1
const ZIGZAG_HORIZONTAL_AMPLITUDE := 60.0
const HELPER_ROCKET_COUNT := 10
const HELPER_ROCKET_DAMAGE := 45.0
const HELPER_ROCKET_DELAY_MIN := 0.2
const HELPER_ROCKET_DELAY_MAX := 2.0
const HELPER_ROCKET_SPEED_MULT := 1.3
const HELPER_ROCKET_SPEED_VARIANCE_MIN := 0.85
const HELPER_ROCKET_SPEED_VARIANCE_MAX := 1.2
const HELPER_ROCKET_MIN_SEPARATION := 56.0
const PICKUP_DROP_CHANCE := 0.195
const BARRIER_METEORITE_SCALE := 0.11
const BARRIER_HITS_TO_DESTROY := 3
const BARRIER_FALL_SPEED_MIN := 90.0
const BARRIER_FALL_SPEED_MAX := 180.0
const BARRIER_ROTATION_SPEED_MIN := -5.0
const BARRIER_ROTATION_SPEED_MAX := 5.0
const PENTA_SHOT_DURATION := 10.0
const PENTA_SHOT_SPREAD := 0.45
const HIT_GLOW_DURATION := 0.5
const SHIELD_HALO_SCALE := 1.92

# Player
const PLAYER_MAX_HP := 100.0
const ENEMY_CONTACT_DAMAGE := 20.0

# Score
const SCORE_PER_KILL := 10
const SCORE_PER_LEVEL := 50

# Pickups
const PICKUP_SCALE := 1.7
const WEAPON_PICKUP_DURATION := 10.0
const SHIELD_PICKUP_DURATION := 22.0
const TRIPLE_PICKUP_DURATION := 16.0
const TRIPLE_SHOT_SPREAD := 0.35
const WEAPON_BOOST_DIVISOR := 3.0
const SPEED_BOOST_MULTIPLIER := 1.6

# Enemy shooter
const SHOOTER_FIRE_INTERVAL := 3.0

# Wave spawning
const ENEMY_SPAWN_DELAY := 0.075
const ENEMY_WAVE_VERTICAL_STAGGER := 35.0

static func is_past_hud_combat_line(global_y: float) -> bool:
	return global_y >= HUD_COMBAT_START_Y
